### ISSUE TITLE
💡Feature: toggleMenu in navbar

### ISSUE THREAD

**Issue by raghchawla131** [MilanCommunity/Milan#1099] opened 2023-10-01 10:04 UTC
### Description

When toggling the menu in navbar on smaller screens, its happening too quick which isn't looking good. it would look better with some kind of animation effect.

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (blank for no)

**Comment by Edantuti** [comment] 2023-10-01 10:34
I am willing to work on this issue.

**Comment by Arun-cn** [comment] 2023-10-01 12:32
hey i like to work on this issue

**Comment by tamalCodes** [comment] 2023-10-02 16:08
Hi @Arun-cn @raghchawla131 we do not need this feature as of now. Please do not make PRs when the status of the issue is still in https://github.com/MilanCommunity/Milan/labels/%F0%9F%9F%A3%20status%3A%20todo - I will be closing this issue and the PR. 

Thanks.

**Closed by tamalCodes** 2023-10-02 16:08 UTC
Labels: 💡 feature, hacktoberfest, 🟣 status: todo
