### ISSUE TITLE
Bug: Navbar Issue after Logged In

### ISSUE THREAD

**Issue by RajBhattacharyya** [milancommunity/Milan#1091] opened 2023-09-30 16:26 UTC
### Description

**Description:**
- **Issue:** 
     The profile button in the navbar is not functioning as expected.

- **Expected Behavior:**
     Clicking on the profile button should navigate to the user's profile page or logout me out directly.

- **Actual Behavior:**
      When clicking on the profile button, it is taking me to error page 404.

- **Steps to Reproduce:**
  1. Log in to the application.
  2. Click on the profile button in the navbar.
  3. Note it's redirecting to error page

### Screenshots

![image](https://github.com/MilanCommunity/Milan/assets/113163315/210f601f-4400-4dfe-bee7-cac046e99eb9)
![image](https://github.com/MilanCommunity/Milan/assets/113163315/b83d09ba-866c-4c7d-b54c-6305763443d3)

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no).

**Comment by Vijaykv5** [comment] 2023-10-01 13:05
Hey I would love to work on this issue.
May you can assign me under hacktoberfest label

**Comment by tamalCodes** [comment] 2023-10-06 08:15
Hey @RajBhattacharyya , thanks for raising the issue. Apologies for the delay that has been made. 
Can you please take a look at the following recording, that would make you understand what's going on better.

https://www.loom.com/share/e659725c8d0f41069be4613dcaf0ee3d?sid=d9bc167c-bcdf-4612-a540-8d2eb297b4a5

**Comment by RajBhattacharyya** [comment] 2023-10-07 19:29
Hello @tamalCodes I have few questions to ask..
1. We have to update the backend where we'll take the userType input during the Google auth?
2. If we do so then we have to update the frontend too asking the user to login as individual or clubs...
3. Or we can just use Google auth for individual only... or club login only?

**Comment by tamalCodes** [comment] 2023-10-07 19:55
Take a look [here](https://github.com/MilanCommunity/Milan-Backend/blob/f458a3c82372d81c7e5c031e2ea6609b49ed8f80/config/passport-googleAuth-strategy.js#L22). We are using `Passport js` to take care of the google authentication, so we need to set up a google auth strategy for the same.

We have 2 types of users, and that is the reason why in our account we have a `usertype` field. Now here's the problem:

 We apparently cannot make 2 different strategies for Google auth, nor can we pass proper data to the backend for this case. Therefore we are stuck with the `await User.create`  - meaning whenever anyone creates an account with Google auth, they will be given an `user` account only. Not a `club` account.

<br/>
<br/>

So as you noticed there is a huge flaw where if I try to make a club account with Google Auth, the register won't work. That is why I have thought of 2 approaches:

As soon as the user logs in with OAuth, we pass a `OAuthLoginInitiated` cookie from the [/google/callback backend route](https://github.com/MilanCommunity/Milan-Backend/blob/f458a3c82372d81c7e5c031e2ea6609b49ed8f80/routes/user/Auth.js#L161) which is [checked in the Frontend here](https://github.com/MilanCommunity/Milan/blob/a5be3e675151b2920168a2aec1e1d0a0b8939db7/src/pages/Home.jsx#L25), if we have that cookie we call a function which simply calls the [/login/success backend route](https://github.com/MilanCommunity/Milan-Backend/blob/f458a3c82372d81c7e5c031e2ea6609b49ed8f80/routes/user/Auth.js#L180C13-L180C25) and that route passes the `emptyProfile` cookie to the Frontend if there is no `usertype` in the user's data.


What I have thought is to give an option to the user as soon as they would visit their profile, if they would have the `emptyProfile` cookie we will give them the option to choose which type of account they want and obviously they can't go back if they once choose. So that way it would work.

The next thing is I am trying to find a way if by any means i can have 2 different google Auth strategies or something similar.

**Comment by RajBhattacharyya** [comment] 2023-10-08 07:35
Hey @tamalCodes of the 2 approaches you said I think:

1.  First approach, we are letting the user create a incomplete profile first, them we are letting them edit.
2. Second approach, we are create 2 different AUTH strategies which is not necessary.

How about we do this like this:

1. When the user click on sign in with google button we first show them a dialog box to select the userType after that auth screen will appear. Along with this extra parameter, we send the data to google as custom inputs

     **OR**

2. We create 2 different buttons in the signup page only, one for Individual other for clubs. and same extra parameter will then pass to google auth

**Comment by tamalCodes** [comment] 2023-10-08 09:56
That's the problem we are facing. We are unable to `send the data to google as custom inputs` . If that was possible then this error would have been solved easily too. We can simply configure the buttons to send the usertype - but that is not working. 

I would rather be grateful if you could head over to the [Milan Backend](https://github.com/MilanCommunity/Milan-Backend/) repo and try if this would work out in any way.

**Comment by dev0869** [comment] 2024-01-02 06:55
Hey I would like to work on this issue.

**Comment by tamalCodes** [comment] 2024-01-11 15:13
Go ahead @dev0869  !
Keep me posted with the updates if possible

**Comment by Vinaysohaliya** [comment] 2024-01-13 07:26
I would like to work on this issue on 15th Jan, can you assign me.

**Comment by tamalCodes** [comment] 2024-01-13 07:28
Hi @Vinaysohaliya this issue is currently https://github.com/milancommunity/Milan/labels/status%3A%20wip%20%F0%9F%91%A9%F0%9F%8F%BB%E2%80%8D%F0%9F%92%BB meaning someone is working on it - I'll wait for a while before I transfer issues !

**Comment by Vijaykv5** [comment] 2024-01-13 07:44
@tamalCodes as per your contribution guidelines, it is first come first basis.
I addressed to work on this issue at first you may see earlier comments and you have assigned to someone after that 
:(

**Comment by tamalCodes** [comment] 2024-01-13 14:11
Hi, @Vijaykv5 Yes we do assign issues on a first come first serve basis but do take a look at this cheque box that everyone has to fill whenever they make an issue in this case the author of the original issue has checked that box and was active at that current time that was the reason why I did not assign you the issue back then.

Hope you get the reason as to why you weren't assigned. Anyway, open source is not about competing for different issues rather if you want to go ahead and contribute to our project do take a look at other open issues or raise a new one and I will happily assign you that.

![image](https://github.com/milancommunity/Milan/assets/72851613/6c9e25ae-b7d6-4f29-9a61-d7c73287e7a4)

**Comment by Vijaykv5** [comment] 2024-01-13 14:17
@tamalCodes Yeah I saw that but I'm talking about after he's unassigned. 
Like after you unassigned him, it must be the next first one right to be assigned according to repo contributing guideline

I completely agree open source is not about competing, but following a contributing guidelines is also most important in open source.

**Comment by tamalCodes** [comment] 2024-01-13 15:02
So here's exactly where things go wrong I do not keep track in that manner of who came after whom and I do assign the issues based on the latest comment or the latest person I see in this case it was not you. 

If I had to keep track of who came after whom things would be complicated now imagine a scenario - Where I first assign an issue on September 30th the work then gets started and someone comments in October, or November while the issue is still WIP.

Next, I became inactive and I came back the next year after my health was ok now I try to close all these stale issues because I feel that it is now really complicated to track back into history and cope with the work that is there instead I try and create fresh issues - Now just a week ago I see someone else comment so I went ahead and assign them instead of assigning someone who commented 3 months ago.

Why ?

Because there might be very high chances of that person not being active anymore in this particular thread. So instead of wasting more time on the already delayed issue (4 month long issue in this case) - I go ahead and assign someone relatively new to get the task done.

This is exactly the reason why I said open source is not about competing with issues but rather trying to understand what went along with the maintainer and why they couldn't make it up & collaborate more.

I hope you understand - I'll mark all our comments as off-topic for now.

**Comment by tamalCodes** [comment] 2024-02-27 03:58
# Notice 🚩

Hi there, unfortunately, I will have to close this Issue/PR, as this issue/PR has been inactive for quite a while and there's no work going on for the same.

There might be more Issues/PR that are waiting for this to be completed - so it is better to pace things up. I generally spend/wait for 3 weeks before marking any issue as stale and closing it.

If you think that this is a mistake, please drop an email at milanhub.org@gmail.com, and we will get back to you.

Regards, 
Team Milan.

**Closed by tamalCodes** 2024-02-27 03:58 UTC
Labels: 🐞 bug, status: wip 👩🏻‍💻
